DRAFT: `anib` issue_123
widdowquinn/pyani pull request #338
Opened 2021-09-13 23:32 UTC by baileythegreen

Please include a summary of the change and which issue is fixed. Please also include the motivation and context, and note the tests that apply to these changes.

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality not to work as expected)
- [ ] This change requires a documentation update
- [ ] This is a documentation update

## Action Checklist

- [ ] Work on a single issue/concept (if there are multiple separate issues to address, please use a separate pull request for each)
- [ ] Fork the `pyani` repository under your own account (please [allow write access for repository maintainers](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork))
- [ ] Set up an appropriate development environment (please see `CONTRIBUTING.md`)
- [ ] Create a new branch with a short, descriptive name
- [ ] Work on this branch
  - [ ] style guidelines have been followed
  - [ ] new code is commented, especially in hard-to-understand areas
  - [ ] corresponding changes to documentation have been made
  - [ ] tests for the change have been added that demonstrate the fix or feature works
- [ ] Test locally with `pytest -v` **non-passing code will not be merged**
- [ ] Rebase against `origin/master`
- [ ] Check changes with `flake8` and `black` before submission
- [ ] Commit branch
- [ ] Submit pull request, describing the content and intent of the pull request
- [ ] Request a code review
- [ ] Continue the discussion at [`Pull requests` section](https://github.com/widdowquinn/pyani/pulls) in the `pyani` repository

2021-09-14 16:30 UTC, baileythegreen commented
I am running into an issue:

- In the monolithic v2, `anib` and `aniblastall` were conjoined; we discussed separating them for v3.
- `pyani/scripts/average_nucleotide_identity.py` exists in the v3 branch, and both it, and its tests, expect `anib` and `aniblastall` to be conjoined.

As of yet, I am not sure how to separate the two, while keeping backwards-compatibility and also not repeating a lot of code.

2021-09-14 21:22 UTC, baileythegreen commented
I have resolved the issue with the legacy script in a way that I consider to be elegant; that works; and is fairly clear, but also only changes internals. However, it causes a minor problem with either `flake8` or CodeFactor. `flake8` doesn't seem to register the `__import__()` command as adding something to the namespace; and CodeFactor complains about the `global` statement I had to add to satisfy `flake8` so I could commit.

It passes all tests, though; and kept the changes to a minimum.

2021-09-22 23:19 UTC, baileythegreen commented
Reminder to myself that this is currently missing `test_aniblastall.py`, which probably explains (most of) the decrease in coverage.

2021-10-05 17:03 UTC, baileythegreen commented
Failing test for `get_version()` on Linux because the information is in stdout, not stderr.

2022-05-16 23:30 UTC, baileythegreen commented
> @widdowquinn I think this is ready to merge. The things being caught by codefactor are calls to `subprocess.run` that use `shell=True`, which I don't think we can do differently, and the use of `global anib` in `average_nucleotide_identity.py`, which is necessary to maintain backwards compatibility so the legacy tests pass.

This is once again the state of this PR. Can it be merged?

2022-06-07 17:07 UTC, widdowquinn requested changes
If tests are no longer relevant or applicable, they should be removed or updated to make them relevant. The "unsure this is needed" message here ([cc4d346](https://github.com/widdowquinn/pyani/pull/338/commits/cc4d3465798e9df5612d1c2dc133893d5a72c1b3)) reads as though the person making the change does not know what the test does, and/or why it fails or might be important.

In this case, the intent of the tests was to supplement the corresponding `*single()` function (which tests generation of a single command line, given input files), to check whether the appropriate reciprocal BLAST comparison command lines were being correctly generated. This allowed some level of diagnosis when a comparison fails to establish that it is not (i) the command-line itself that fails or (ii) failure to generate the reciprocal comparison command-lines.

These are unit tests, whose coverage may be masked by a passing integration test so removal may not indicate a problem if only the coverage information is being checked. Please can you clarify whether the intent of these skipped tests was maintained elsewhere? If not, do you consider that any of the following hold: (i) the unit test is redundant; (ii) the unit test needs to be updated to reflect the new way that reciprocal comparison commands are generated; (iii) the time taken to update the unit tests would be better spent converting command-line generation to something SLURM-compatible?

If (i) then please delete the tests. If (ii) please update the tests accordingly. If (iii) please ignore - other than to note that (iii) is the case - and work on the new command-line generation.

2025-07-01 13:57 UTC, closed without merging