Fix a typo in logging message & redundant f-string usage
widdowquinn/pyani pull request #354
Opened 2021-11-15 12:29 UTC by peterjc

Noticed while investigating #353 for which I intend to add a little more logging.

## Type of change

- [X] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality not to work as expected)
- [ ] This change requires a documentation update
- [ ] This is a documentation update

## Action Checklist

- [X] Work on a single issue/concept (if there are multiple separate issues to address, please use a separate pull request for each)
- [X] Fork the `pyani` repository under your own account (please [allow write access for repository maintainers](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork))
- [X] Set up an appropriate development environment (please see `CONTRIBUTING.md`)
- [X] Create a new branch with a short, descriptive name
- [X] Work on this branch
  - [X] style guidelines have been followed
  - [ ] new code is commented, especially in hard-to-understand areas
  - [ ] corresponding changes to documentation have been made
  - [ ] tests for the change have been added that demonstrate the fix or feature works
- [ ] Test locally with `pytest -v` **non-passing code will not be merged**
- [X] Rebase against `origin/master`
- [X] Check changes with `flake8` and `black` before submission
- [X] Commit branch
- [X] Submit pull request, describing the content and intent of the pull request
- [ ] Request a code review
- [ ] Continue the discussion at [`Pull requests` section](https://github.com/widdowquinn/pyani/pulls) in the `pyani` repository

2021-11-15 12:33 UTC, peterjc commented
Interesting - CodeFactor flagged one of these changes was in unreachable code following ``raise NotImplementedError``

2021-11-15 12:50 UTC, baileythegreen commented
@peterjc CodeFactor is flagging the change in `anib` because that subcommand hasn't been implemented yet in `master`. There is an `anib_123` branch where it is. We won't be concerned with the warning here.

2021-11-18 17:31 UTC, baileythegreen requested changes
I have left some changes I would like to see (in line with style cleaning changes I've been working on)  in comments. Once the changes are made, this can be merged.

2021-11-18 18:06 UTC, widdowquinn commented
Sorry to jump in here, but AFAIAA we should not use f-strings in `logging` calls. There is more info at https://docs.python.org/3/howto/logging-cookbook.html#use-of-alternative-formatting-styles but essentially string formatting is deferred until it cannot be avoided, and f-strings format early, as explained here: https://klichx.dev/2019/11/09/f-strings-and-python-logging/

2021-11-18 18:12 UTC, widdowquinn requested changes
Please don't use f-strings for logger messages.

2021-11-18 19:41 UTC, baileythegreen commented
@widdowquinn Okay, I didn't realise that was a considered choice for optimisation of the logging. I'll go back and look at where I might have changed logging strings and fix them.

@peterjc Sorry for the confusion. If you can revert the last commit, then I can merge it.

2021-11-18 20:46 UTC, widdowquinn commented
> @widdowquinn Okay, I didn't realise that was a considered choice for optimisation of the logging. I'll go back and look at where I might have changed logging strings and fix them.

It isn't just optimisation either - some tools (e.g. monitoring tools like Sentry) catch the log strings - for instance to group messages on the basis of identical patterns. When messages get concretised with values _before_ the call to `logger` this isn't possible.

2021-11-18 23:28 UTC, peterjc commented
Reverted. Interesting reading, thank you.

2021-11-19 11:24 UTC, baileythegreen commented on pyani/scripts/subcommands/subcmd_anib.py
> +    logger.info(f"\t...total pairwise comparisons to be performed: {len(comparisons)}")
```suggestion
    logger.info("\t...total pairwise comparisons to be performed: %s", len(comparisons))
```

2021-11-19 13:17 UTC, merged